import { describe,it,expect } from "vitest";
import { QuoteSchema,ListingDetailsSchema,OwnerDetailsSchema,emptyDetails } from "../../src/contracts/listing-details";
import { costSummary,quoteCost } from "../../src/lib/tourism/cost";
import details from "../../data/listing-details.json";
import { SignupSchema,BusinessInputSchema,PublicUrlSchema } from "../../src/contracts/accounts";
const quote=QuoteSchema.parse({id:"price",label_ar:"اختبار",amount_fils:8125,unit:"per_person",status:"owner_declared",audience:"everyone",conditions:[],source_url:null,checked_at:null,optional:false});
describe("conditional listing costs",()=>{
 it("uses integer fils for people, group and room-nights",()=>{expect(quoteCost(quote,4,3,2)).toBe(32500);expect(quoteCost({...quote,unit:"per_group"},4,3,2)).toBe(8125);expect(quoteCost({...quote,unit:"per_night"},4,3,2)).toBe(48750);});
 it("never treats unspecified units or invalid counts as zero",()=>{expect(quoteCost({...quote,unit:"unspecified"},4,2,1)).toBeNull();for(const people of [0,-1,1.5,31,NaN])expect(quoteCost(quote,people,1,1)).toBeNull();expect(costSummary([],4,1,1).total_fils).toBeNull();expect(costSummary([quote,{...quote,unit:"unspecified"}],4,1,1).total_fils).toBeNull();});
 it("labels estimated totals without upgrading them to source prices",()=>{expect(costSummary([{...quote,status:"demo_estimate"}],4,1,1)).toMatchObject({estimated:true,total_fils:32500});});
 it("validates the full details dataset, conditions and source evidence",()=>{for(const row of Object.values(details))expect(ListingDetailsSchema.safeParse(row).success).toBe(true);expect(QuoteSchema.safeParse({...quote,amount_fils:1.5}).success).toBe(false);expect(QuoteSchema.safeParse({...quote,status:"source_checked"}).success).toBe(false);});
 it("preserves Petra visitor categories instead of assigning all visitors one fee",()=>{const prices=details["60000000-0000-4000-8000-000000000001"].quotes;expect(prices.find(q=>q.audience==="jordanian")?.amount_fils).toBe(1000);expect(prices.find(q=>q.audience==="international_day")?.amount_fils).toBe(90000);expect(prices.find(q=>q.audience==="resident")?.conditions.join(" ")).toContain("سنة");});
 it("does not infer nightly billing for EcoPark",()=>{const q=QuoteSchema.parse(details["60000000-0000-4000-8000-000000000014"].quotes[0]);expect(q.unit).toBe("unspecified");expect(quoteCost(q,4,3,1)).toBeNull();});
 it("disallows owner claims of verified prices and unlicensed media",()=>{expect(OwnerDetailsSchema.safeParse({...emptyDetails,quotes:[quote]}).success).toBe(true);expect(OwnerDetailsSchema.safeParse({...emptyDetails,quotes:[{...quote,status:"source_checked",source_url:"https://example.com",checked_at:new Date().toISOString()}]}).success).toBe(false);expect(OwnerDetailsSchema.safeParse({...emptyDetails,image_url:"https://example.com/photo.jpg"}).success).toBe(false);});
});
describe("account input boundary",()=>{
 it("validates signup and rejects forged actor fields",()=>{const input={display_name:"زائر",account_type:"traveler",email:"test@example.com",password:"test-only-123"};expect(SignupSchema.safeParse(input).success).toBe(true);expect(SignupSchema.safeParse({...input,owner_id:crypto.randomUUID()}).success).toBe(false);expect(SignupSchema.safeParse({...input,password:"123"}).success).toBe(false);});
 it("does not accept executable, local or credential-bearing links",()=>{for(const url of ["javascript:alert(1)","http://example.com","https://localhost/image.jpg","https://127.0.0.1/x","https://name:password@example.com/x"])expect(PublicUrlSchema.safeParse(url).success).toBe(false);expect(PublicUrlSchema.safeParse("https://example.com/image.jpg").success).toBe(true);});
 it("prevents client assignment of ownership or verification",()=>{const b={name:"مشروع محلي",description:"تجربة سياحية من أهل المكان",location_id:"irbid",category:"طبيعة",phone:null,whatsapp:null,website:null,social_url:null};expect(BusinessInputSchema.safeParse(b).success).toBe(true);expect(BusinessInputSchema.safeParse({...b,owner_id:crypto.randomUUID()}).success).toBe(false);expect(BusinessInputSchema.safeParse({...b,verification_status:"contact_checked"}).success).toBe(false);});
});
