import { beforeEach, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { emptyBusinessSettings, PublicBusinessSettingsSchema } from "../../src/contracts/settings";
const mocks = vi.hoisted(() => ({ client: vi.fn() }));
vi.mock("@/lib/supabase/server", () => ({ createClient: mocks.client }));
import { GET } from "../../src/app/api/businesses/[id]/settings/route";
const id = "00000000-0000-4000-8000-000000000098", context = { params: Promise.resolve({ id }) };
const publicSettings = { business_id: id, name_en: null, service_area: [], activity_types: [], profile_image_url: null, minimum_group_size: 1, maximum_group_size: null, price_range_min_fils: null, price_range_max_fils: null, license_status: "yes", license_verification_status: "unverified" };
beforeEach(() => { vi.resetAllMocks(); vi.stubEnv("DATA_MODE", "supabase"); });
it("reads only a whitelisted public projection without private licensing fields", async () => { const select = vi.fn().mockReturnThis(), eq = vi.fn().mockReturnThis(), chain = { select, eq, maybeSingle: async () => ({ data: publicSettings, error: null }) }, from = vi.fn(() => chain); mocks.client.mockResolvedValue({ from }); const response = await GET(new Request("http://localhost:3000"), context); expect(response.status).toBe(200); expect((await response.json()).data).toEqual(publicSettings); expect(from).toHaveBeenCalledWith("public_business_settings"); expect(eq).toHaveBeenCalledWith("business_id", id); for (const field of ["registration_number", "licensing_authority", "license_expires_on", "owner_id"])
    expect(select.mock.calls[0][0]).not.toContain(field); });
it("fails closed if a future projection accidentally adds a private field", async () => { mocks.client.mockResolvedValue({ from: () => ({ select() { return this; }, eq() { return this; }, maybeSingle: async () => ({ data: { ...publicSettings, registration_number: "PRIVATE" }, error: null }) }) }); const response = await GET(new Request("http://localhost:3000"), context); expect(response.status).toBe(503); expect(JSON.stringify(await response.json())).not.toContain("PRIVATE"); expect(PublicBusinessSettingsSchema.safeParse({ ...emptyBusinessSettings, business_id: id, license_verification_status: "unverified" }).success).toBe(false); });
it("seed mode returns unknown licensing without a database or fictitious declaration", async () => { vi.stubEnv("DATA_MODE", "seed"); expect((await (await GET(new Request("http://localhost:3000"), context)).json()).data).toBeNull(); expect(mocks.client).not.toHaveBeenCalled(); });
it("migration declares RLS and separates public columns from license evidence (static review only)", () => { const sql = readFileSync("supabase/migrations/006_preferences_business_settings.sql", "utf8"); expect(sql).toContain("enable row level security"); const projection = sql.split("create view public.public_business_settings")[1].split("from public.business_settings")[0]; for (const privateField of ["registration_number", "licensing_authority", "license_expires_on", "owner_id"])
    expect(projection).not.toContain(privateField); const ownerGrants = sql.split("grant insert(business_id")[1].split("on public.business_settings")[0]; expect(ownerGrants).not.toContain("license_verification_status"); });
