import { beforeEach, expect, it, vi } from "vitest";
import { BusinessSettingsSchema, UserPreferencesSchema, emptyBusinessSettings, emptyPreferences, licenseLabels } from "../../src/contracts/settings";
import { HttpError } from "../../src/lib/http";
const mocks = vi.hoisted(() => ({ user: vi.fn(), business: vi.fn() }));
vi.mock("@/lib/auth/server", () => ({ requireUser: mocks.user, requireBusiness: mocks.business }));
import { PATCH as preferences, GET as readPreferences } from "../../src/app/api/account/preferences/route";
import { PATCH as settings, GET as readSettings } from "../../src/app/api/business/settings/route";
const origin = "http://localhost:3000", user = "00000000-0000-4000-8000-000000000099", business = "00000000-0000-4000-8000-000000000098";
const request = (input: unknown, site = origin) => new Request(origin, { method: "PATCH", headers: { Origin: site, "Content-Type": "application/json" }, body: JSON.stringify(input) });
beforeEach(() => { vi.resetAllMocks(); vi.stubEnv("APP_ORIGIN", origin); });
it("derives the preference owner from verified Auth", async () => { const upsert = vi.fn().mockResolvedValue({ error: null }); mocks.user.mockResolvedValue({ id: user, client: { from: () => ({ upsert }) } }); expect((await preferences(request(emptyPreferences))).status).toBe(200); expect(upsert).toHaveBeenCalledWith({ user_id: user, payload: emptyPreferences }); expect((await preferences(request({ ...emptyPreferences, user_id: business }))).status).toBe(400); expect(upsert).toHaveBeenCalledTimes(1); });
it("loads default preferences only when no preference row exists", async () => { const eq = vi.fn().mockReturnThis(), chain = { eq, select: vi.fn().mockReturnThis(), maybeSingle: vi.fn().mockResolvedValue({ data: null, error: null }) }; mocks.user.mockResolvedValue({ id: user, client: { from: () => chain } }); expect((await (await readPreferences()).json()).data).toEqual(emptyPreferences); expect(eq).toHaveBeenCalledWith("user_id", user); });
it("license declaration cannot write another owner or a verified status", async () => { const upsert = vi.fn().mockResolvedValue({ error: null }); mocks.business.mockResolvedValue({ business: { id: business }, client: { from: () => ({ upsert }) } }); expect((await settings(request({ ...emptyBusinessSettings, license_status: "yes", registration_number: "PRIVATE-123" }))).status).toBe(200); expect(upsert).toHaveBeenCalledWith(expect.objectContaining({ business_id: business, license_status: "yes" })); expect(upsert.mock.calls[0][0]).not.toHaveProperty("license_verification_status"); for (const field of [{ business_id: user }, { owner_id: user }, { license_verification_status: "verified" }])
    expect((await settings(request({ ...emptyBusinessSettings, ...field }))).status).toBe(400); expect(upsert).toHaveBeenCalledTimes(1); expect(licenseLabels.yes).toContain("لم نتحقق"); });
it.each([401, 403])("unauthorized settings requests return %i without a write", async (status) => { mocks.business.mockRejectedValue(new HttpError(status, "FORBIDDEN", "Denied")); expect((await settings(request(emptyBusinessSettings))).status).toBe(status); });
it("missing migration fails explicitly rather than claiming successful storage", async () => { mocks.business.mockResolvedValue({ business: { id: business }, client: { from: () => ({ upsert: async () => ({ error: { message: "missing table" } }) }) } }); expect((await settings(request(emptyBusinessSettings))).status).toBe(503); });
it("reads private license settings with the derived business scope", async () => { const eq = vi.fn().mockReturnThis(), chain = { eq, select: vi.fn().mockReturnThis(), maybeSingle: vi.fn().mockResolvedValue({ data: { ...emptyBusinessSettings, license_status: "yes", registration_number: "PRIVATE-123", license_verification_status: "unverified" }, error: null }) }; mocks.business.mockResolvedValue({ business: { id: business }, client: { from: () => chain } }); expect((await (await readSettings()).json()).data.settings.registration_number).toBe("PRIVATE-123"); expect(eq).toHaveBeenCalledWith("business_id", business); });
it("rejects cross-origin writes before authorization", async () => { expect((await preferences(request(emptyPreferences, "https://other.example"))).status).toBe(403); expect(mocks.user).not.toHaveBeenCalled(); });
it("validates image rights, group range, private license consistency and integer prices", () => { for (const patch of [{ profile_image_url: "https://example.com/image.jpg" }, { minimum_group_size: 5, maximum_group_size: 2 }, { price_range_min_fils: 1000, price_range_max_fils: 999 }, { price_range_min_fils: 1000.5, price_range_max_fils: 2000 }, { license_status: "no", registration_number: "SECRET" }, { activity_types: ["destination"] }])
    expect(BusinessSettingsSchema.safeParse({ ...emptyBusinessSettings, ...patch }).success).toBe(false); expect(UserPreferencesSchema.safeParse({ ...emptyPreferences, preferred_group_size: 31 }).success).toBe(false); });
