import { z } from "zod";
import { ActivitySchema, CategorySchema, GroupTypeSchema, LocationIdSchema } from "./index";
import { CatalogMetadataSchema, ListingKindSchema, DiscoveryTagSchema } from "./catalog";

// Expanded geography is additive; never send these new IDs through API v1.
export const TourismLocationSchema = z.enum([...LocationIdSchema.options, "pella", "jordan-valley", "dead-sea", "wadi-mujib", "main", "mount-nebo", "baptism-site", "petra", "aqaba"]);
export const tourismLocations: Record<z.infer<typeof TourismLocationSchema>, string> = { amman: "عمّان", irbid: "إربد", ajloun: "عجلون", jerash: "جرش", "umm-qais": "أم قيس", "as-salt": "السلط", madaba: "مادبا", dana: "ضانا وفينان", "wadi-rum": "وادي رم", pella: "طبقة فحل / بيلا", "jordan-valley": "الأغوار الشمالية", "dead-sea": "البحر الميت", "wadi-mujib": "وادي الموجب", main: "حمامات ماعين", "mount-nebo": "جبل نيبو", "baptism-site": "المغطس", petra: "البتراء / وادي موسى", aqaba: "العقبة" };
export const TourismActivitySchema = z.strictObject({ ...ActivitySchema.shape, location_id: TourismLocationSchema }).refine(v => v.price_unit === "unknown" ? v.price_fils === null : v.price_unit === "free" ? v.price_fils === 0 : v.price_fils !== null && v.price_fils > 0, { path:["price_fils"], message:"Unknown requires no price; free requires zero; paid units require a positive price." });
export const LicensedImageSchema = z.strictObject({ path: z.string().regex(/^\/images\/tourism\/[a-z0-9-]+\.jpg$/), title: z.string().min(1), alt_ar: z.string().min(1), author: z.string().min(1), license: z.string().regex(/^CC (BY|BY-SA) (2\.0|2\.5|3\.0|4\.0)$|^CC0 1\.0$|^Public domain$/), license_url: z.url(), source_url: z.url(), original_url: z.url(), downloaded_from: z.url(), changes: z.string().min(1), checked_at: z.iso.datetime({ offset: true }) });
export const TourismProviderSchema = z.strictObject({ id: z.uuid(), name: z.string().min(1).max(200), website: z.url().nullable(), source_url: z.url().nullable(), verification_status: z.enum(["source_checked", "owner_declared", "unverified"]) }).refine(v=>v.verification_status !== "source_checked" || v.source_url !== null, {message:"Source-checked provider identity requires evidence."});
export const TourismListingSchema = z.strictObject({ activity: TourismActivitySchema, metadata: CatalogMetadataSchema, provider: TourismProviderSchema.nullable(), image: LicensedImageSchema.nullable(), currency: z.literal("JOD"), location_label_ar: z.string().min(1).max(200), location_label_en: z.string().min(1).max(200), coordinates: z.strictObject({ latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), source_url: z.url() }).nullable() })
    .refine(v => v.metadata.listing_kind !== "destination" || (v.activity.business_id === null && v.provider === null && v.activity.record_kind === "place"), { message: "Public destinations have no private owner." })
    .refine(v => v.metadata.listing_kind !== "business_offer" || (v.activity.business_id !== null && v.activity.record_kind === "offer"), { message:"A business offer requires its actual provider reference." })
    .refine(v => v.metadata.estimated_price_fils === null || v.activity.price_unit === "unknown", {message:"Estimates cannot replace a declared price."})
    .refine(v => v.activity.verification_status !== "source_checked" || v.activity.source_url !== null, {message:"Source-checked introductions require evidence."})
    .refine(v => v.provider === null || v.provider.id === v.activity.business_id, { message: "Provider must match the referenced business." })
    .refine(v => v.image === null ? v.activity.image_path === null : v.activity.image_path === v.image.path, { message: "Photo requires matching license evidence." });
export const TourismFiltersSchema = z.strictObject({ query: z.string().max(1000).default(""), location_id: TourismLocationSchema.optional(), listing_kind: ListingKindSchema.optional(), category: CategorySchema.optional(), tag: DiscoveryTagSchema.optional(), party_size: z.number().int().min(1).max(30).optional(), group_type: GroupTypeSchema.optional(), budget_fils: z.number().int().min(0).max(10000000).optional() });
export const TourismResponseSchema = z.strictObject({ data: z.array(TourismListingSchema), meta: z.strictObject({ count: z.number().int().nonnegative(), total: z.number().int().nonnegative(), unconfirmed_count: z.number().int().nonnegative(), data_mode: z.enum(["seed", "supabase"]), engine: z.literal("rules_discovery") }) });
export type TourismListing = z.infer<typeof TourismListingSchema>;
export type TourismFilters = z.infer<typeof TourismFiltersSchema>;
export type LicensedImage = z.infer<typeof LicensedImageSchema>;
