// Local UI verification. No real Auth, DB writes or paid AI requests.
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const origin=process.env.SMOKE_ORIGIN||'http://localhost:3100';
const debug=process.env.CHROME_DEBUG_ORIGIN||'http://127.0.0.1:9225';
const target=await fetch(`${debug}/json/new?${encodeURIComponent(origin)}`,{method:'PUT'}).then(r=>r.json());
const socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});
let next=0;const requests=new Map(),exceptions=[];
socket.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params);if(m.id&&requests.has(m.id)){const {resolve,reject,timer}=requests.get(m.id);clearTimeout(timer);requests.delete(m.id);if(m.error)reject(new Error(m.error.message));else resolve(m.result);}});
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++next,timer=setTimeout(()=>reject(new Error(`CDP timeout ${method}`)),20000);requests.set(id,{resolve,reject,timer});socket.send(JSON.stringify({id,method,params}));});}
async function ev(expression){const result=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.text);return result.result.value;}
async function wait(expression){const end=Date.now()+25000;while(Date.now()<end){if(await ev(`Boolean(${expression})`))return;await new Promise(r=>setTimeout(r,120));}throw new Error(`UI timeout ${expression}`);}
async function set(id,value){await ev(`(()=>{const el=document.getElementById(${JSON.stringify(id)});if(!el)throw new Error('Missing field ${id}');const proto=el.tagName==='SELECT'?HTMLSelectElement.prototype:el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));})()`);}
async function nav(path){await call('Page.navigate',{url:origin+path});await wait('document.readyState==="complete"');}
async function shot(name){await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false}).then(r=>writeFile(`.qa-artifacts/final/${name}.png`,Buffer.from(r.data,'base64')));}
await call('Page.enable');await call('Runtime.enable');await call('Network.enable');await mkdir('.qa-artifacts/final',{recursive:true});await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await nav('/');await wait("document.querySelectorAll('.tourism-section .tourism-card').length===6");await ev('localStorage.clear()');await call('Page.reload');await wait("document.querySelectorAll('.tourism-section .tourism-card').length===6");assert.equal(await ev('document.documentElement.dir'),'rtl');assert.ok(await ev("document.getElementById('hero-title').textContent.includes('اكتشف الأردن')"));await shot('home-desktop');
await nav('/listings/60000000-0000-4000-8000-000000000001');await wait("document.querySelector('.cost-calculator') && document.querySelector('.listing-cover img')?.naturalWidth>0");await set('cost-people','4');assert.ok(await ev("document.querySelector('.cost-total').textContent.includes('4 د.أ')"));await set('quote','day');await set('cost-budget','60');assert.ok(await ev("document.querySelector('.cost-total').textContent.includes('360 د.أ') && document.querySelector('.cost-total').textContent.includes('يتجاوز')"));await set('cost-people','0');assert.ok(await ev("document.querySelector('.cost-total').textContent.includes('تواصل')"));await set('cost-people','4');await shot('petra-prices-desktop');
await ev("Object.defineProperty(navigator,'share',{value:undefined,configurable:true});Object.defineProperty(navigator,'clipboard',{value:{writeText:async value=>window.sharedUrl=value},configurable:true});[...document.querySelectorAll('button')].find(b=>b.textContent.includes('مشاركة المكان')).click()");await wait('window.sharedUrl===location.href');
await nav('/listings/60000000-0000-4000-8000-000000000014');await wait("document.querySelector('.cost-calculator')");assert.ok(await ev("document.querySelector('.quote-description').textContent.includes('45 د.أ') && document.querySelector('.cost-total').textContent.includes('تواصل')"));assert.equal(await ev("!!document.getElementById('cost-nights')"),false);
await nav('/listings/71000000-0000-4000-8000-000000000105');await wait("document.getElementById('cost-nights')");await set('cost-nights','2');await set('cost-rooms','2');assert.ok(await ev("document.querySelector('.cost-total').textContent.includes('260 د.أ') && document.querySelector('.quote-description').textContent.includes('تقدير تجريبي')"));
await nav('/listings/60000000-0000-4000-8000-000000000005');await wait("document.querySelectorAll('.photo-thumbnails button').length===2");await ev("document.querySelector('.photo-thumbnails button').click();document.querySelector('.card-explore').click()");await wait("!!document.querySelector('dialog[open]')");assert.ok(await ev("document.querySelector('dialog[open]').contains(document.activeElement)"));await ev("[...document.querySelectorAll('dialog[open] button')].find(b=>b.textContent==='التالية').click()");assert.ok(await ev("document.querySelector('.gallery-large img').alt.includes('الجمال')"));await shot('gallery-desktop');await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await wait("!document.querySelector('dialog[open]')");await nav('/listings/60000000-0000-4000-8000-000000000002');await wait("!!document.querySelector('.cost-calculator')");assert.ok(await ev("!!document.querySelector('a[href^=\"https://www.google.com/maps/dir/\"]')"));assert.ok(await ev("[...document.querySelectorAll('.related-card')].every(a=>a.href.includes('/listings/'))"));
await nav('/signup');await wait("!!document.querySelector('.account-choice')");await ev("document.querySelectorAll('.account-choice')[1].click()");await wait("document.querySelectorAll('.account-choice')[1].getAttribute('aria-pressed')==='true'");await ev("[...document.querySelectorAll('button')].find(b=>b.textContent==='بدء تجربة محلية').click()");await wait("!!document.getElementById('business-name')");assert.ok(await ev("!!document.querySelector('.demo-banner')"));await set('business-name','مشروع الدروب التجريبي');await set('business-description','تجربة طبيعة افتراضية لاختبار العرض على هذا المتصفح فقط');await set('business-category','طبيعة وهايكنغ');await ev("document.querySelector('form').requestSubmit()");await wait("document.querySelector('[role=status]')?.textContent.includes('المتصفح')");await shot('business-profile');
await nav('/business/manage');await wait("!!document.getElementById('listing-title')");await set('listing-title','طلعة الدروب المحلية التجريبية');await set('listing-description','مسار طبيعة افتراضي في إربد لتجربة الاكتشاف والنشر المحلي فقط');await set('listing-price','8');await set('listing-capacity','8');await ev("document.querySelector('form').requestSubmit()");await wait("!!document.querySelector('.manager-grid section article')");assert.ok(await ev("document.querySelector('[role=status]').textContent.includes('المتصفح فقط')"));const listingId=await ev("JSON.parse(localStorage.getItem('jordan-local-local-demo-v2')).listings[0].activity.id");await call('Page.reload');await wait("document.querySelector('.manager-grid section article')?.textContent.includes('طلعة الدروب')");await shot('manager-desktop');
await nav('/explore?tour_query='+encodeURIComponent('طلعة الدروب المحلية التجريبية')+'&tour_location_id=irbid&tour_party_size=4&tour_budget=60');await wait("[...document.querySelectorAll('.tourism-section .tourism-card')].some(c=>c.textContent.includes('طلعة الدروب'))");assert.ok(await ev("[...document.querySelectorAll('.tourism-section .tourism-card')].find(c=>c.textContent.includes('طلعة الدروب')).textContent.includes('32 د.أ')"));await set('city','irbid');await set('party','4');await set('budget','60');await ev("document.querySelector('.recommendation-form').requestSubmit()");await wait("document.querySelector('.local-demo-recommendations')?.textContent.includes('طلعة الدروب')");assert.ok(await ev("document.querySelector('.local-demo-recommendations').textContent.includes('32')"));await nav('/listings/'+listingId);await wait("document.querySelector('h1')?.textContent.includes('طلعة الدروب')");await set('cost-people','4');assert.ok(await ev("document.querySelector('.cost-total').textContent.includes('32 د.أ')"));await ev("[...document.querySelectorAll('button')].find(b=>b.textContent.includes('احفظ المكان')).click()");await wait("[...document.querySelectorAll('button')].some(b=>b.textContent.includes('♥ محفوظ'))");await nav('/saved');await wait("document.querySelector('.tourism-card')?.textContent.includes('طلعة الدروب')");
await nav('/businesses/00000000-0000-4000-8000-000000000010');await wait("document.querySelector('h1')?.textContent.includes('مشروع الدروب')");
await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await nav('/listings/'+listingId);await wait("!!document.querySelector('.cost-calculator')");assert.ok(await ev('document.documentElement.scrollWidth<=innerWidth+1'));await shot('local-detail-mobile');await nav('/business/manage');await wait("!!document.getElementById('listing-title')");assert.ok(await ev('document.documentElement.scrollWidth<=innerWidth+1'));await shot('manager-mobile');
await ev("[...document.querySelectorAll('.manager-grid section article button')].find(b=>b.textContent==='تعديل').click()");await set('listing-title','طلعة الدروب بعد التعديل');await ev("document.querySelector('form').requestSubmit()");await wait("document.querySelector('.manager-grid section article h3')?.textContent.includes('بعد التعديل')");await ev("window.confirm=()=>true;[...document.querySelectorAll('.manager-grid section article button')].find(b=>b.textContent==='أرشفة').click()");await wait("document.querySelectorAll('.manager-grid section article').length===0");await nav('/listings/'+listingId);await wait("document.querySelector('h1')?.textContent.includes('لم نتمكن')");await nav('/account');await wait("!!document.getElementById('profile-name')");await ev("[...document.querySelectorAll('header button')].find(b=>b.textContent==='خروج').click()");await wait("!document.querySelector('.demo-banner')");assert.equal(await ev("localStorage.getItem('jordan-local-local-demo-v2')"),null);assert.equal(exceptions.length,0,JSON.stringify(exceptions));
console.log(JSON.stringify({passed:true,flows:['RTL landing','conditional prices','nightly arithmetic','unknown billing period','gallery next/escape','share handler (clipboard stub)','source-linked directions','local business profile','publish and reload','budget-filtered discovery','favorites','provider profile','edit/archive','logout','mobile layout'],realAuth:false,realDatabase:false,paidAI:false,screenshots:'.qa-artifacts/final'},null,2));
socket.close();await fetch(`${debug}/json/close/${target.id}`);
