// Regenerate only additive catalogue demo files; never modifies the original seed.
import { readFileSync, writeFileSync } from "node:fs";
const original = JSON.parse(readFileSync("data/activities.seed.json", "utf8"));
const metadata = original.map(a => ({ activity_id: a.id, metadata: { listing_kind: "activity", discovery_tags: a.tags.map(t => t === "culture" ? "cultural" : t === "heritage" ? "historical" : t), estimated_price_fils: null, estimated_price_unit: null } }));
for (const index of [0,1,9]) metadata[index].metadata.discovery_tags.push("hiking");
metadata[6].metadata.discovery_tags.push("scenic");
const rows = [];
const stamp = "2026-10-09T00:00:00Z";
function add(number, changes, kind, tags, estimate = null) {
    const row = { ...original[0], id: `30000000-0000-4000-8000-${String(number).padStart(12,"0")}`, ...changes, created_at: stamp, updated_at: stamp };
    rows.push(row);
    metadata.push({ activity_id: row.id, metadata: { listing_kind: kind, discovery_tags: tags, estimated_price_fils: estimate, estimated_price_unit: estimate === null ? null : "per_group" } });
}
add(1, { business_id: null, record_kind: "place", title_ar: "أم قيس — آثار وإطلالات", title_en: "Umm Qais — ruins and views", description_ar: "وجهة عامة تجمع آثار جدارا والإطلالات على وادي الأردن. المعلومات التعريفية من هيئة تنشيط السياحة؛ رسوم الدخول والسعة والمدة والتوافر غير مؤكدة هنا.", description_en: "Public destination. Introduction sourced from Jordan Tourism Board; admission and availability unconfirmed.", location_id: "umm-qais", category: "heritage", tags: ["heritage","nature"], environment: ["countryside"], group_types: [], family_friendly: null, capacity_people: null, duration_minutes: null, available_months: null, price_fils: null, price_unit: "unknown", price_status: "unknown", price_checked_at: null, price_notes: "رسوم الدخول تختلف ولا نقدم سعرًا مؤكدًا. ليست مجانية لمجرد عدم وجود سعر.", source_url: "https://international.visitjordan.com/wheretogo/umm-qais/", location_source_url: "https://international.visitjordan.com/wheretogo/umm-qais/", data_kind: "public_source", verification_status: "source_checked", source_checked_at: stamp }, "destination", ["historical","scenic","cultural","nature"]);
add(2, { business_id: null, record_kind: "place", title_ar: "قلعة عجلون — وجهة تاريخية", title_en: "Ajloun Castle — historic destination", description_ar: "قلعة تاريخية على مرتفع في عجلون. وصف الوجهة مستند إلى هيئة تنشيط السياحة؛ لم نؤكد رسوم الدخول أو ملاءمة المجموعة أو التوافر.", description_en: "Public historic destination. Introduction sourced from Jordan Tourism Board; prices and availability unconfirmed.", location_id: "ajloun", category: "heritage", tags: ["heritage","culture"], environment: ["countryside"], group_types: [], family_friendly: null, capacity_people: null, duration_minutes: null, available_months: null, price_fils: null, price_unit: "unknown", price_status: "unknown", price_checked_at: null, price_notes: "رسوم الدخول غير مؤكدة؛ تحقق من المصدر الرسمي قبل الزيارة.", source_url: "https://international.visitjordan.com/whattodo/history-culture/", location_source_url: "https://international.visitjordan.com/whattodo/history-culture/", data_kind: "public_source", verification_status: "source_checked", source_checked_at: stamp }, "destination", ["historical","scenic","cultural"]);
add(3, { title_ar: "مزرعة ومسبح — مثال افتراضي", title_en: "Farm and pool — fictional demo", description_ar: "مثال افتراضي لمكان زيارة نهارية مع مسبح. ليس منشأة حقيقية؛ السعر والسعة تجريبيان، ولا يؤكد الوصف السلامة أو الإشراف.", location_id: "irbid", category: "nature", tags: ["nature"], environment: ["countryside"], price_fils: 35000, price_unit: "per_group", capacity_people: 8 }, "visitable_place", ["farms","pools","swimming","family","wellness"]);
add(4, { title_ar: "كوخ ريفي — تقدير تجريبي", title_en: "Country cabin — demo estimate", description_ar: "مثال إقامة افتراضي لعرض الفرق بين تقدير السعر والسعر المؤكد. لا توجد إقامة حقيقية أو سعر ليلة مؤكد؛ يلزم تحديد المدة والتواصل قبل اتخاذ قرار.", category: "nature", tags: ["nature"], price_fils: null, price_unit: "unknown", price_status: "unknown", price_checked_at: null, price_notes: "تقدير افتراضي لحزمة المجموعة فقط، وليس سعر ليلة مؤكدًا." }, "accommodation", ["cabins","wellness","scenic","couples"], 60000);
add(5, { title_ar: "حزمة غروب ومخيم — مثال افتراضي", title_en: "Sunset and camp package — demo", description_ar: "حزمة نهارية افتراضية في أجواء الصحراء مع جلسة في مخيم. لا تشمل مبيتًا، ولا تتبع شركة حقيقية ولا تقبل الحجز.", location_id: "wadi-rum", environment: ["desert"], price_fils: 30000, price_unit: "per_group", capacity_people: 10 }, "business_offer", ["camps","scenic","local_tours","adventure"]);
writeFileSync("data/tourism.seed.json", JSON.stringify(rows,null,2) + "\n");
writeFileSync("data/catalog.seed.json", JSON.stringify(metadata,null,2) + "\n");
const sql = `-- Run after migrations 001/002 and seed.sql. Additive; existing rows preserved.\nbegin;\ninsert into public.activities select * from json_populate_recordset(null::public.activities,$tourism$${JSON.stringify(rows)}$tourism$) on conflict(id) do nothing;\ninsert into public.catalog_metadata(activity_id,listing_kind,discovery_tags,estimated_price_fils,estimated_price_unit)\nselect activity_id,(metadata->>'listing_kind'),array(select jsonb_array_elements_text(metadata->'discovery_tags')),(metadata->>'estimated_price_fils')::integer,metadata->>'estimated_price_unit'\nfrom jsonb_to_recordset($catalog$${JSON.stringify(metadata)}$catalog$::jsonb) as x(activity_id uuid,metadata jsonb) on conflict(activity_id) do nothing;\ncommit;\n`;
writeFileSync("supabase/seed_catalog.sql",sql);
